//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusManagement1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int animal_id { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public decimal weight { get; set; }
        public string food_preferences { get; set; }
        public string care_recommendations { get; set; }
        public int trainer_id { get; set; }
        public int cage_id { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
